### ISSUE TITLE
Nouvelle raison de refus de CET/EXP

### ISSUE THREAD

**Issue by SmokkeyEZ** [marceaupatu123/departement-scientifique#30]
Mettre une nouvelle raison de refus de CET/EXP via le bot « Vous n’avez pas l’accréditation requise » ou un truc du genre.

**Comment by marceaupatu123** [comment]
> Mettre une nouvelle raison de refus de CET/EXP via le bot « Vous n’avez pas l’accréditation requise » ou un truc du genre.

Alors je veux bien mais techniquement ça rentre pas dans la case "Non respect des PCS" ?

**Comment by SmokkeyEZ** [comment]
C'est possible mais je trouve le "nom respect des PCS" trop flou au final. Je sais pas si c'est que moi mais voilà je me permets de proposer du coup, à toi de voir :)

**Comment by marceaupatu123** [comment]
> C'est possible mais je trouve le "nom respect des PCS" trop flou au final. Je sais pas si c'est que moi mais voilà je me permets de proposer du coup, à toi de voir :)

Très bien ce sera ajouté alors !
