### ISSUE TITLE
Suggestion Bot CET

### ISSUE THREAD

**Issue by WalixTv** [marceaupatu123/departement-scientifique#31]
**Description de l'ajout**
Le but de cette ajout et de pouvoir permettre au bot de faire une liste des CET sur les SCP présent InGame et que y’aura 2 bouton, le premier pour dire que le CET a été effectué et le deuxième pour dire que le CET doit être fait en urgence et tout les 2 heure le CET d’un SCP se reset et aussi on a la possibilité de voir qui a fait le CET puis sa se met dans les logs: le format 

SCP : XXXX                         (image du SCP)
Unités requis : X-AIT / X-Classe D
Matériel : …………….

**Comment by WalixTv** [comment]
![](https://user-images.githubusercontent.com/40667906/218308499-4c1d896b-a438-4cc5-9a31-198d6e60777e.png)
 

bah c’est sa que je veut dire

**Comment by marceaupatu123** [comment]
Héhé c'est #3 eft
