### ISSUE TITLE
Demande pour les absence 

### ISSUE THREAD

**Issue by WalixTv** [marceaupatu123/departement-scientifique#5]
**Description de l'ajout**
Veuillez faire une description détaillé de ce que vous voulez ajouter au bot.

**Comment by marceaupatu123** [comment]
@WalixTv Une description un peu plus détaillée serait appréciée ^^

**Comment by WalixTv** [comment]
Bah sa va resembler un peu comme la commande pour demande d’exp mais pour les absence. Voice le forma de demande d’absence ;

Nom RP :  
Grade : 
Date : Du ../../…. au ../../….
Raison :

**Comment by WalixTv** [comment]
@marceaupatu123

**Comment by marceaupatu123** [comment]
Ok ça me semble bon ! Je met ça dans le projet.

**Comment by marceaupatu123** [comment]
Il faut rajouter un affichage embed
